name: Build Dify API Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch:

env:
  DOCKERHUB_REPO: registry.cn-hangzhou.aliyuncs.com/kindlingx/apo-dify-api
  REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  CONTAINER_NAME: dify-api
  DEPLOYMENT_NAME: apo-dify-api
  NAMESPACE: apo

jobs:
  build-image:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      IMAGE_TAG_NAME: ${{ steps.build-image.outputs.IMAGE_TAG_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image metadata
        id: build-image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          DATE=$(date +"%Y%m%d%H%M%S%Z")
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed 's#[^a-zA-Z0-9._-]#-#g')
          IMAGE_TAG_NAME="${BRANCH_NAME}-${COMMIT_HASH::7}-${DATE}"
          echo "IMAGE_TAG_NAME=$IMAGE_TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "IMAGE_FULL_TAG_AMD64=${{ env.REGISTRY_HOST }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:${IMAGE_TAG_NAME}" >> $GITHUB_ENV  
          echo "IMAGE_FULL_TAG_ARM64=${{ env.REGISTRY_HOST }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:${IMAGE_TAG_NAME}-arm64" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ env.IMAGE_FULL_TAG_AMD64 }}

  deploy-dev:
    runs-on: [self-hosted, dev]
    needs: [build-image]
    steps:
    - name: Deploy to dev
      env: 
        IMAGE_TAG_NAME: ${{ needs.build-image.outputs.IMAGE_TAG_NAME }}
      run: |
        IMAGE_FULL_NAME="${{ env.REGISTRY_HOST }}/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DEPLOYMENT_NAME }}:$IMAGE_TAG_NAME"
        echo "IMAGE_FULL_NAME=$IMAGE_FULL_NAME"
        export KUBECONFIG="/root/.kube/config"
        kubectl set image statefulset ${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=$IMAGE_FULL_NAME -n ${{ env.NAMESPACE }}
        kubectl set image statefulset apo-dify-worker dify-worker=$IMAGE_FULL_NAME -n ${{ env.NAMESPACE }}